/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EchipaRouteImport } from './routes/echipa'
import { Route as TarifeServiciiRouteImport } from './routes/tarife-servicii'
import { Route as ServiciiDermatovenerologieRouteImport } from './routes/servicii.dermatovenerologie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EchipaRoute = EchipaRouteImport.update({
  id: '/echipa',
  path: '/echipa',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifeServiciiRoute = TarifeServiciiRouteImport.update({
  id: '/tarife-servicii',
  path: '/tarife-servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiDermatovenerologieRoute =
  ServiciiDermatovenerologieRouteImport.update({
    id: '/servicii/dermatovenerologie',
    path: '/servicii/dermatovenerologie',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/echipa': typeof EchipaRoute
  '/tarife-servicii': typeof TarifeServiciiRoute
  '/servicii/dermatovenerologie': typeof ServiciiDermatovenerologieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/echipa': typeof EchipaRoute
  '/tarife-servicii': typeof TarifeServiciiRoute
  '/servicii/dermatovenerologie': typeof ServiciiDermatovenerologieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/echipa': typeof EchipaRoute
  '/tarife-servicii': typeof TarifeServiciiRoute
  '/servicii/dermatovenerologie': typeof ServiciiDermatovenerologieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/echipa'
    | '/tarife-servicii'
    | '/servicii/dermatovenerologie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/echipa'
    | '/tarife-servicii'
    | '/servicii/dermatovenerologie'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/echipa'
    | '/tarife-servicii'
    | '/servicii/dermatovenerologie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EchipaRoute: typeof EchipaRoute
  TarifeServiciiRoute: typeof TarifeServiciiRoute
  ServiciiDermatovenerologieRoute: typeof ServiciiDermatovenerologieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echipa': {
      id: '/echipa'
      path: '/echipa'
      fullPath: '/echipa'
      preLoaderRoute: typeof EchipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarife-servicii': {
      id: '/tarife-servicii'
      path: '/tarife-servicii'
      fullPath: '/tarife-servicii'
      preLoaderRoute: typeof TarifeServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii/dermatovenerologie': {
      id: '/servicii/dermatovenerologie'
      path: '/servicii/dermatovenerologie'
      fullPath: '/servicii/dermatovenerologie'
      preLoaderRoute: typeof ServiciiDermatovenerologieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EchipaRoute: EchipaRoute,
  TarifeServiciiRoute: TarifeServiciiRoute,
  ServiciiDermatovenerologieRoute: ServiciiDermatovenerologieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
